name: build

on:
  push:
    branches:
      - master
  workflow_dispatch: {}
  repository_dispatch: {}

jobs:
  build:
    if: github.repository == 'JekyllNet/minimal-mistakes'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Build docs with JekyllNet
      uses: JekyllNet/action@main
      with:
        source: ./docs
        destination: ./artifacts/docs-site
        upload-artifact: "true"
        artifact-name: minimal-mistakes-docs
